name: harukaprotect
build:
  type: nodejs
  command: npm install --production=false
run:
  command: npm start
env:
  - name: NODE_ENV
    value: production
healthcheck:
  http:
    port: 8000
    path: /
  grace_period: 30
  interval: 15
  restart_limit: 3
  timeout: 10
