name: harukaprotect
build:
  type: nodejs
  buildCommand: npm install
run:
  command: node index.js
env:
  - name: NODE_ENV
    value: production
healthcheck:
  http:
    port: 8000
    path: /
  grace_period: 30
  interval: 15
  restart_limit: 3
  timeout: 10